services:
  postgres:
    image: postgres:latest
    restart: always
    environment: 
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=PrimaryDB
    ports:
      - '5432:5432'

  server:
    build: .
    restart: always
    ports:
      - '8080:8080'
    depends_on:
      - postgres
    volumes:
      - logs:/var/app/logs
      - messages:/var/app/messages
